# Generated by Django 6.1 on 2026-09-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=255)),
                ('hospital_code', models.CharField(max_length=50, unique=True)),
                ('hospital_type', models.CharField(choices=[('PRIMARY', 'Primary Care Hospital'), ('SECONDARY', 'Secondary / General Hospital'), ('TERTIARY', 'Tertiary / Level 3 Medical Center'), ('SPECIALTY', 'Specialty Hospital'), ('APEX_TRAUMA', 'Apex Trauma Center')], default='TERTIARY', max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('contact_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255)),
                ('emergency_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('operating_status', models.CharField(choices=[('OPERATIONAL', 'Fully Operational'), ('LIMITED', 'Limited Capacity'), ('EMERGENCY_ONLY', 'Emergency Only'), ('MAINTENANCE', 'Under Maintenance'), ('CLOSED', 'Closed')], default='OPERATIONAL', max_length=30)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=30)),
                ('bed_capacity', models.PositiveIntegerField(default=100)),
                ('available_beds', models.PositiveIntegerField(default=20)),
                ('icu_capacity', models.PositiveIntegerField(default=10)),
                ('available_icu_beds', models.PositiveIntegerField(default=2)),
                ('authorized_rep_name', models.CharField(blank=True, max_length=150, null=True)),
                ('authorized_rep_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facilities', models.ManyToManyField(blank=True, related_name='hospitals', to='hospitals.facility')),
                ('services', models.ManyToManyField(blank=True, related_name='hospitals', to='hospitals.medicalservice')),
                ('specialties', models.ManyToManyField(blank=True, related_name='hospitals', to='hospitals.specialty')),
            ],
        ),
    ]
