# Generated by Django 6.1 on 2026-09-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='diversion_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hospital',
            name='on_call_specialists',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='hospital',
            name='temporary_penalties',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
