# Generated by Django 6.1 on 2026-09-03 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_ref_no', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('emergency_status', models.BooleanField(default=False)),
                ('current_condition', models.CharField(max_length=255)),
                ('clinical_summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_patients', to='hospitals.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(max_length=64, unique=True)),
                ('urgency', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('EMERGENCY', 'Emergency')], default='ROUTINE', max_length=20)),
                ('reason_for_referral', models.TextField()),
                ('additional_requirements', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('MORE_INFORMATION_REQUIRED', 'More Information Required'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('TRANSFER_PENDING', 'Transfer Pending'), ('TRANSFER_ASSIGNED', 'Transfer Assigned'), ('DISPATCHED', 'Dispatched'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED', 'Arrived'), ('HANDED_OVER', 'Handed Over'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=35)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('more_info_request_notes', models.TextField(blank=True, null=True)),
                ('more_info_response_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_referrals', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='referrals.patient')),
                ('receiving_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_referrals', to='hospitals.hospital')),
                ('requesting_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_referrals', to='hospitals.hospital')),
                ('required_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='hospitals.facility')),
                ('required_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='hospitals.medicalservice')),
                ('required_specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='hospitals.specialty')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('REFERRAL_LETTER', 'Referral Letter'), ('MEDICAL_SUMMARY', 'Medical Summary'), ('LAB_RESULT', 'Laboratory Result'), ('IMAGING_REPORT', 'Imaging Report (X-Ray/CT/MRI)'), ('OTHER', 'Other Clinical Document')], default='REFERRAL_LETTER', max_length=30)),
                ('file', models.FileField(upload_to='referral_docs/%Y/%m/%d/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='referrals.referral')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=35)),
                ('to_status', models.CharField(max_length=35)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='referrals.referral')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
