# Generated by Django 6.1 on 2026-09-05 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0002_hospital_diversion_status_and_more'),
        ('referrals', '0002_referralmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinatorOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_code', models.CharField(choices=[('CT_SCAN_OFFLINE', 'CT Scanner / Imaging Down'), ('SURGEON_UNAVAILABLE', 'On-Call Specialist / Surgeon Engaged'), ('EMERGENCY_BAY_SATURATED', 'Emergency Bay at Physical Capacity'), ('EQUIPMENT_MAINTENANCE', 'Critical Equipment in Maintenance'), ('PATIENT_FAMILY_REQUEST', 'Patient or Family Facility Preference'), ('PHYSICIAN_DISCRETION', 'Referring Physician Clinical Discretion'), ('TRANSPORT_CONSTRAINTS', 'Ambulance Travel Time or Corridor Constraint'), ('OTHER', 'Other Clinical / Operational Justification')], default='PHYSICIAN_DISCRETION', max_length=50)),
                ('justification_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coordinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_overrides', to=settings.AUTH_USER_MODEL)),
                ('recommended_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_overrides', to='hospitals.hospital')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_overrides', to='referrals.referral')),
                ('selected_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_overrides', to='hospitals.hospital')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
