# Generated by Django 6.1 on 2026-09-03 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
        ('referrals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_type', models.CharField(default='Advanced Life Support (ALS) Ambulance', max_length=50)),
                ('driver_name', models.CharField(blank=True, max_length=150, null=True)),
                ('driver_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('paramedic_name', models.CharField(blank=True, max_length=150, null=True)),
                ('pickup_location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('TRANSFER_PENDING', 'Transfer Pending'), ('TRANSFER_ASSIGNED', 'Transfer Assigned'), ('DISPATCHED', 'Dispatched'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED', 'Arrived'), ('HANDED_OVER', 'Handed Over'), ('COMPLETED', 'Completed')], default='TRANSFER_PENDING', max_length=30)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('in_transit_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('handed_over_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('handover_notes', models.TextField(blank=True, null=True)),
                ('problem_reports', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='hospitals.hospital')),
                ('dispatcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_transfers', to=settings.AUTH_USER_MODEL)),
                ('referral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer', to='referrals.referral')),
            ],
        ),
    ]
